name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container:
      image: debian:buster
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git curl libglib2.0-dev wget xz-utils pkg-config curl jq

      - name: Install Go
        run: |
          curl -L https://golang.org/dl/go1.21.0.linux-amd64.tar.gz | tar -C /usr/local -xz
          echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Install Frida Core devkit
        run: |
          FRIDA_VERSION="16.3.1"
          FRIDA_DEVKIT="frida-core-devkit-${FRIDA_VERSION}-linux-x86_64.tar.xz"
          wget -q "https://github.com/frida/frida/releases/download/${FRIDA_VERSION}/${FRIDA_DEVKIT}" -O - | tar -xJ -C /tmp
          mkdir -p /usr/local/include/frida /usr/local/lib
          cp /tmp/frida-core.h /usr/local/include/frida/
          ln -sf /usr/local/include/frida/frida-core.h /usr/local/include/frida-core.h
          cp /tmp/libfrida-core.a /usr/local/lib/
          ldconfig

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build for Linux AMD64
        env:
          CGO_ENABLED: 1
          CGO_CFLAGS: "-Wno-error=incompatible-pointer-types -I/usr/local/include"
          CGO_LDFLAGS: "-L/usr/local/lib"
          GOARCH: "amd64"
          GOOS: "linux"
        run: |
          mkdir -p build
          go mod tidy
          go build -buildvcs=false -ldflags "-s -w" -o build/frida-injector_linux_amd64 .
          cd build
          tar -czvf frida-injector_linux_amd64.tar.gz frida-injector_linux_amd64
          sha256sum frida-injector_linux_amd64{,.tar.gz} > frida-injector_linux_amd64.sha256
          sha256sum frida-injector_linux_amd64.tar.gz > frida-injector_linux_amd64.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/frida-injector_linux_amd64
            build/frida-injector_linux_amd64.tar.gz
            build/frida-injector_linux_amd64.tar.gz.sha256
            build/frida-injector_linux_amd64.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
