name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build for Linux (Debian Buster)
    runs-on: ubuntu-latest
    container:
      image: debian:buster
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install Git and build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git curl libglib2.0-dev wget xz-utils pkg-config

      - name: Install Go
        run: |
          curl -L https://golang.org/dl/go1.21.0.linux-amd64.tar.gz -o go.tar.gz
          tar -C /usr/local -xzf go.tar.gz
          echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Install Frida Core devkit
        run: |
          # Install specific Frida version required for the project
          FRIDA_VERSION="16.3.1"
          FRIDA_DEVKIT="frida-core-devkit-${FRIDA_VERSION}-linux-x86_64.tar.xz"
          FRIDA_URL="https://github.com/frida/frida/releases/download/${FRIDA_VERSION}/${FRIDA_DEVKIT}"
          
          echo "Downloading Frida Core devkit ${FRIDA_VERSION}..."
          mkdir -p /tmp/frida-devkit
          wget -q $FRIDA_URL -O /tmp/frida-devkit/${FRIDA_DEVKIT}
          
          cd /tmp/frida-devkit
          tar -xf ${FRIDA_DEVKIT}
          
          # Copy header to include directory
          mkdir -p /usr/local/include/frida
          cp frida-core.h /usr/local/include/frida/
          
          # Create symlink for compatibility
          ln -sf /usr/local/include/frida/frida-core.h /usr/local/include/frida-core.h
          
          # Copy library to lib directory
          mkdir -p /usr/local/lib
          cp libfrida-core.a /usr/local/lib/
          
          # Refresh linker cache
          ldconfig
          
          echo "Frida Core devkit installed successfully"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build for Linux AMD64
        env:
          CGO_ENABLED: 1
          CGO_CFLAGS: "-Wno-error=incompatible-pointer-types -I/usr/local/include"
          CGO_LDFLAGS: "-L/usr/local/lib"
          GOARCH: "amd64"
          GOOS: "linux"
        run: |
          mkdir -p build
          go mod tidy
          go build -buildvcs=false -ldflags "-s -w" -o build/frida-injector_linux_amd64 .
          cd build
          tar -czvf frida-injector_linux_amd64.tar.gz frida-injector_linux_amd64
          sha256sum frida-injector_linux_amd64.tar.gz > frida-injector_linux_amd64.tar.gz.sha256
          sha256sum frida-injector_linux_amd64 > frida-injector_linux_amd64.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frida-injector-artifacts
          path: build/
          retention-days: 1

  create-release:
    name: Create Release
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: frida-injector-artifacts
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/frida-injector_linux_amd64
            artifacts/frida-injector_linux_amd64.tar.gz
            artifacts/frida-injector_linux_amd64.tar.gz.sha256
            artifacts/frida-injector_linux_amd64.sha256
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}